"""Generate the ClimateInputBuf lane list for the lane-boundary diagnostic.

Same reason as gen_round_scalar_fields.py: a hand-written list is how overlay
gaps survive. The diagnostic needs to name the lane, so the list is generated
from the struct.

Run: python tools/runtime/gen_input_lane_fields.py
Writes: gdext/src/runtime_climate_input_lane_fields.inc
"""
import io
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
HEADER = os.path.join(ROOT, "gdext", "src", "runtime_climate_passes.h")
OUT = os.path.join(ROOT, "gdext", "src", "runtime_climate_input_lane_fields.inc")

LANE = re.compile(r"^\s*std::vector<\s*(float|int32_t|uint8_t|double)\s*>\s+(\w+)\s*;")


def main() -> None:
    text = io.open(HEADER, encoding="utf-8").read()
    start = text.index("struct ClimateInputBuf {")
    depth = 0
    end = start
    for i in range(start, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                end = i
                break
    body = text[start:end]

    lanes = []
    for line in body.split("\n"):
        if line.strip().startswith("//"):
            continue
        m = LANE.match(line)
        if m:
            lanes.append((m.group(2), m.group(1)))

    if len(lanes) < 20:
        raise SystemExit("only found %d lanes, struct parse likely wrong" % len(lanes))

    lines = [
        "// GENERATED by tools/runtime/gen_input_lane_fields.py -- do not edit.",
        "// PK_INPUT_LANE(name, element_type) per ClimateInputBuf per-cell lane.",
        "",
    ]
    lines += ["PK_INPUT_LANE(%s, %s)" % (n, t) for n, t in lanes]
    lines.append("")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print("wrote %s with %d lanes" % (OUT, len(lanes)))


if __name__ == "__main__":
    main()
