"""Generate the ClimateRoundScalars field list used by the scalar-boundary diagnostic.

The diagnostic has to name every field it compares, and a hand-written list goes
stale the moment someone adds a knob -- which is exactly how the overlay gaps got
in. Regenerating from the struct definition keeps the two in step.

Run: python tools/runtime/gen_round_scalar_fields.py
Writes: gdext/src/runtime_climate_round_scalar_fields.inc
"""
import io
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
HEADER = os.path.join(ROOT, "gdext", "src", "runtime_climate_passes.h")
OUT = os.path.join(ROOT, "gdext", "src", "runtime_climate_round_scalar_fields.inc")

FIELD = re.compile(
    r"^\s*(?:float|double|int|bool|int32_t|uint32_t|uint8_t)\s+(\w+)\s*(?:=[^;]*)?;")


def main() -> None:
    text = io.open(HEADER, encoding="utf-8").read()
    start = text.index("struct ClimateRoundScalars {")
    depth = 0
    end = start
    for i in range(start, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                end = i
                break
    body = text[start:end]

    names = []
    for line in body.split("\n"):
        stripped = line.strip()
        if stripped.startswith("//"):
            continue
        m = FIELD.match(line)
        if m:
            names.append(m.group(1))

    if len(names) < 40:
        raise SystemExit("only found %d fields, struct parse likely wrong" % len(names))

    lines = [
        "// GENERATED by tools/runtime/gen_round_scalar_fields.py -- do not edit.",
        "// One PK_ROUND_SCALAR(name) per ClimateRoundScalars field, so the scalar",
        "// boundary diagnostic can name a mismatching knob instead of reporting a",
        "// hash difference.",
        "",
    ]
    lines += ["PK_ROUND_SCALAR(%s)" % n for n in names]
    lines.append("")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print("wrote %s with %d fields" % (OUT, len(names)))


if __name__ == "__main__":
    main()
