// component_bind_table.gen.h — AUTOGENERATED by tools/codegen/gen_cpp_bind_table.py
//
// DO NOT EDIT THIS FILE BY HAND. Edit the GDScript single source at
//   Project/project-keynes/scripts/data_core/component_schema.gd
// then run
//   python3 Project.Keynes/tools/codegen/gen_cpp_bind_table.py
// and rebuild the GDExtension. The script enforces uniqueness of
// cpp_name / map_field and validates dtype values; any drift between
// schema and generated header is a build-time error, not a silent
// runtime miscompile.
//
// This file is the single C++-side mirror of the GDScript bind_map_data
// registration. Background and rationale: docs/dots-migration-roadmap.md
// §3 (A1 ComponentSchema 单一源) and dots-component-schema.md.
//
// Schema entries: 142
// (Demo entries are emitted with the same row shape; the GDScript side
// gates them on demo_thermal_gradient_enabled before binding, and the
// C++ bind_map_data already gracefully no-ops on size==0 properties.)

#pragma once

#include "components/slot.h"

namespace pk {

struct BindEntry {
    const char *slot_name;
    const char *property_name;
    SlotDType   dtype;
};

inline constexpr BindEntry BIND_TABLE_AUTOGEN[] = {
    { "cell_temp",                             "temp_arr",                             SlotDType::F32 },
    { "cell_temp_baseline",                    "temp_baseline_arr",                    SlotDType::F32 },
    { "cell_temp_30d",                         "temp_30d_arr",                         SlotDType::F32 },
    { "cell_temp_365d",                        "temp_365d_arr",                        SlotDType::F32 },
    { "cell_temp_anomaly",                     "temp_anomaly_arr",                     SlotDType::F32 },
    { "cell_moisture",                         "moisture_arr",                         SlotDType::F32 },
    { "cell_snow_cover",                       "snow_cover_arr",                       SlotDType::F32 },
    { "cell_sea_ice_frac",                     "sea_ice_frac_arr",                     SlotDType::F32 },
    { "cell_weather_intensity",                "weather_intensity_arr",                SlotDType::F32 },
    { "cell_weather_cloud",                    "weather_cloud_arr",                    SlotDType::F32 },
    { "cell_weather_cloud_water",              "weather_cloud_water_arr",              SlotDType::F32 },
    { "cell_weather_precip",                   "weather_precip_arr",                   SlotDType::F32 },
    { "cell_weather_transition_alpha",         "weather_transition_alpha_arr",         SlotDType::F32 },
    { "cell_elevation",                        "elevation_arr",                        SlotDType::F32 },
    { "cell_base_moisture",                    "base_moisture_arr",                    SlotDType::F32 },
    { "cell_ocean_current_x",                  "ocean_current_x_arr",                  SlotDType::F32 },
    { "cell_ocean_current_y",                  "ocean_current_y_arr",                  SlotDType::F32 },
    { "cell_wind_x",                           "wind_x_arr",                           SlotDType::F32 },
    { "cell_wind_y",                           "wind_y_arr",                           SlotDType::F32 },
    { "cell_slp",                              "slp_arr",                              SlotDType::F32 },
    { "cell_wind_speed",                       "wind_speed_arr",                       SlotDType::F32 },
    { "cell_upwelling_strength",               "upwelling_strength_arr",               SlotDType::F32 },
    { "cell_wind_stress_curl",                 "wind_stress_curl_arr",                 SlotDType::F32 },
    { "cell_ocean_psi",                        "ocean_psi_arr",                        SlotDType::F32 },
    { "cell_pos_x",                            "cell_pos_x_arr",                       SlotDType::F32 },
    { "cell_pos_y",                            "cell_pos_y_arr",                       SlotDType::F32 },
    { "cell_lat_norm",                         "cell_lat_norm_arr",                    SlotDType::F32 },
    { "cell_temp_baseline_year",               "temp_baseline_year_arr",               SlotDType::F32 },
    { "cell_terrain",                          "terrain_arr",                          SlotDType::U8 },
    { "cell_landform",                         "landform_arr",                         SlotDType::U8 },
    { "cell_vegetation",                       "vegetation_arr",                       SlotDType::U8 },
    { "cell_base_terrain",                     "base_terrain_arr",                     SlotDType::U8 },
    { "cell_base_landform",                    "base_landform_arr",                    SlotDType::U8 },
    { "cell_base_vegetation",                  "base_vegetation_arr",                  SlotDType::U8 },
    { "cell_cover",                            "cover_arr",                            SlotDType::U8 },
    { "cell_weather_type",                     "weather_type_arr",                     SlotDType::U8 },
    { "cell_weather_prev_type",                "weather_prev_type_arr",                SlotDType::U8 },
    { "cell_weather_target_type",              "weather_target_type_arr",              SlotDType::U8 },
    { "cell_is_water",                         "is_water_arr",                         SlotDType::U8 },
    { "cell_country_slot",                     "country_slot_arr",                     SlotDType::I32 },
    { "cell_visible",                          "visible_arr",                          SlotDType::U8 },
    { "cell_explored",                         "explored_arr",                         SlotDType::U8 },
    { "cell_resource_habitat_mask",            "resource_habitat_mask_arr",            SlotDType::U8 },
    { "cell_climate_dirty",                    "climate_dirty_mask",                   SlotDType::U8 },
    { "cell_weather_dirty",                    "weather_dirty_mask",                   SlotDType::U8 },
    { "cell_weather_vapor",                    "weather_vapor_arr",                    SlotDType::F32 },
    { "cell_weather_convergence",              "weather_convergence_arr",              SlotDType::F32 },
    { "cell_weather_instability",              "weather_instability_arr",              SlotDType::F32 },
    { "cell_weather_field_init",               "weather_field_init_arr",               SlotDType::U8 },
    { "cell_air_mass_temp_anomaly",            "air_mass_temp_anomaly_arr",            SlotDType::F32 },
    { "cell_ocean_thermal_anomaly",            "ocean_thermal_anomaly_arr",            SlotDType::F32 },
    { "cell_local_thermal_anomaly",            "local_thermal_anomaly_arr",            SlotDType::F32 },
    { "cell_has_river",                        "has_river_arr",                        SlotDType::U8 },
    { "cell_river_flow",                       "river_flow_arr",                       SlotDType::F32 },
    { "cell_ema_initialized",                  "ema_initialized_arr",                  SlotDType::U8 },
    { "cell_temp_season_offset",               "temp_season_offset_arr",               SlotDType::F32 },
    { "cell_insolation_now",                   "insolation_now_arr",                   SlotDType::F32 },
    { "cell_insolation_dev",                   "insolation_dev_arr",                   SlotDType::F32 },
    { "cell_day_length",                       "day_length_arr",                       SlotDType::F32 },
    { "cell_heat_input",                       "heat_input_arr",                       SlotDType::F32 },
    { "cell_thermal_energy",                   "thermal_energy_arr",                   SlotDType::F32 },
    { "cell_snowpack",                         "snowpack_arr",                         SlotDType::F32 },
    { "cell_water_balance_30d",                "water_balance_30d_arr",                SlotDType::F32 },
    { "cell_vegetation_vitality",              "vegetation_vitality_arr",              SlotDType::F32 },
    { "cell_vitality_low_streak",              "vitality_low_streak_arr",              SlotDType::I32 },
    { "cell_vitality_high_streak",             "vitality_high_streak_arr",             SlotDType::I32 },
    { "cell_soil_moisture",                    "soil_moisture_arr",                    SlotDType::F32 },
    { "cell_vegetation_growth_pressure",       "vegetation_growth_pressure_arr",       SlotDType::F32 },
    { "cell_temperature_transport_anomaly",    "temperature_transport_anomaly_arr",    SlotDType::F32 },
    { "cell_vegetation_heat_stress",           "vegetation_heat_stress_arr",           SlotDType::F32 },
    { "cell_vegetation_drought_stress",        "vegetation_drought_stress_arr",        SlotDType::F32 },
    { "cell_vegetation_cold_stress",           "vegetation_cold_stress_arr",           SlotDType::F32 },
    { "cell_vegetation_regen_score",           "vegetation_regen_score_arr",           SlotDType::F32 },
    { "cell_hydro_parent",                     "hydro_parent_arr",                     SlotDType::I32 },
    { "cell_river_discharge",                  "river_discharge_arr",                  SlotDType::F32 },
    { "cell_river_discharge_30d",              "river_discharge_30d_arr",              SlotDType::F32 },
    { "cell_river_storage",                    "river_storage_arr",                    SlotDType::F32 },
    { "cell_groundwater_storage",              "groundwater_storage_arr",              SlotDType::F32 },
    { "cell_surface_runoff",                   "surface_runoff_arr",                   SlotDType::F32 },
    { "cell_res_timber_reserve",               "res_timber_reserve_arr",               SlotDType::F32 },
    { "cell_res_stone_reserve",                "res_stone_reserve_arr",                SlotDType::F32 },
    { "cell_res_fertile_soil_reserve",         "res_fertile_soil_reserve_arr",         SlotDType::F32 },
    { "cell_res_coal_reserve",                 "res_coal_reserve_arr",                 SlotDType::F32 },
    { "cell_res_oil_reserve",                  "res_oil_reserve_arr",                  SlotDType::F32 },
    { "cell_res_natural_gas_reserve",          "res_natural_gas_reserve_arr",          SlotDType::F32 },
    { "cell_res_copper_ore_reserve",           "res_copper_ore_reserve_arr",           SlotDType::F32 },
    { "cell_res_iron_ore_reserve",             "res_iron_ore_reserve_arr",             SlotDType::F32 },
    { "cell_res_gold_ore_reserve",             "res_gold_ore_reserve_arr",             SlotDType::F32 },
    { "cell_res_silver_ore_reserve",           "res_silver_ore_reserve_arr",           SlotDType::F32 },
    { "cell_res_salt_reserve",                 "res_salt_reserve_arr",                 SlotDType::F32 },
    { "cell_res_saltpeter_reserve",            "res_saltpeter_reserve_arr",            SlotDType::F32 },
    { "cell_res_rare_earth_reserve",           "res_rare_earth_reserve_arr",           SlotDType::F32 },
    { "cell_res_clay_reserve",                 "res_clay_reserve_arr",                 SlotDType::F32 },
    { "cell_res_wild_game_reserve",            "res_wild_game_reserve_arr",            SlotDType::F32 },
    { "cell_res_marine_fish_reserve",          "res_marine_fish_reserve_arr",          SlotDType::F32 },
    { "cell_res_freshwater_fish_reserve",      "res_freshwater_fish_reserve_arr",      SlotDType::F32 },
    { "cell_res_arable_land_reserve",          "res_arable_land_reserve_arr",          SlotDType::F32 },
    { "cell_res_paddy_land_reserve",           "res_paddy_land_reserve_arr",           SlotDType::F32 },
    { "cell_res_plantation_land_reserve",      "res_plantation_land_reserve_arr",      SlotDType::F32 },
    { "cell_res_pasture_reserve",              "res_pasture_reserve_arr",              SlotDType::F32 },
    { "cell_res_bauxite_reserve",              "res_bauxite_reserve_arr",              SlotDType::F32 },
    { "cell_res_limestone_reserve",            "res_limestone_reserve_arr",            SlotDType::F32 },
    { "cell_res_silica_sand_reserve",          "res_silica_sand_reserve_arr",          SlotDType::F32 },
    { "cell_res_phosphate_rock_reserve",       "res_phosphate_rock_reserve_arr",       SlotDType::F32 },
    { "cell_res_tin_ore_reserve",              "res_tin_ore_reserve_arr",              SlotDType::F32 },
    { "cell_res_lead_ore_reserve",             "res_lead_ore_reserve_arr",             SlotDType::F32 },
    { "cell_res_zinc_ore_reserve",             "res_zinc_ore_reserve_arr",             SlotDType::F32 },
    { "cell_res_manganese_ore_reserve",        "res_manganese_ore_reserve_arr",        SlotDType::F32 },
    { "cell_res_sulfur_reserve",               "res_sulfur_reserve_arr",               SlotDType::F32 },
    { "cell_res_flint_reserve",                "res_flint_reserve_arr",                SlotDType::F32 },
    { "cell_res_timber_extra_change",          "res_timber_extra_change_arr",          SlotDType::F32 },
    { "cell_res_stone_extra_change",           "res_stone_extra_change_arr",           SlotDType::F32 },
    { "cell_res_fertile_soil_extra_change",    "res_fertile_soil_extra_change_arr",    SlotDType::F32 },
    { "cell_res_coal_extra_change",            "res_coal_extra_change_arr",            SlotDType::F32 },
    { "cell_res_oil_extra_change",             "res_oil_extra_change_arr",             SlotDType::F32 },
    { "cell_res_natural_gas_extra_change",     "res_natural_gas_extra_change_arr",     SlotDType::F32 },
    { "cell_res_copper_ore_extra_change",      "res_copper_ore_extra_change_arr",      SlotDType::F32 },
    { "cell_res_iron_ore_extra_change",        "res_iron_ore_extra_change_arr",        SlotDType::F32 },
    { "cell_res_gold_ore_extra_change",        "res_gold_ore_extra_change_arr",        SlotDType::F32 },
    { "cell_res_silver_ore_extra_change",      "res_silver_ore_extra_change_arr",      SlotDType::F32 },
    { "cell_res_salt_extra_change",            "res_salt_extra_change_arr",            SlotDType::F32 },
    { "cell_res_saltpeter_extra_change",       "res_saltpeter_extra_change_arr",       SlotDType::F32 },
    { "cell_res_rare_earth_extra_change",      "res_rare_earth_extra_change_arr",      SlotDType::F32 },
    { "cell_res_clay_extra_change",            "res_clay_extra_change_arr",            SlotDType::F32 },
    { "cell_res_wild_game_extra_change",       "res_wild_game_extra_change_arr",       SlotDType::F32 },
    { "cell_res_marine_fish_extra_change",     "res_marine_fish_extra_change_arr",     SlotDType::F32 },
    { "cell_res_freshwater_fish_extra_change", "res_freshwater_fish_extra_change_arr", SlotDType::F32 },
    { "cell_res_arable_land_extra_change",     "res_arable_land_extra_change_arr",     SlotDType::F32 },
    { "cell_res_paddy_land_extra_change",      "res_paddy_land_extra_change_arr",      SlotDType::F32 },
    { "cell_res_plantation_land_extra_change", "res_plantation_land_extra_change_arr", SlotDType::F32 },
    { "cell_res_pasture_extra_change",         "res_pasture_extra_change_arr",         SlotDType::F32 },
    { "cell_res_bauxite_extra_change",         "res_bauxite_extra_change_arr",         SlotDType::F32 },
    { "cell_res_limestone_extra_change",       "res_limestone_extra_change_arr",       SlotDType::F32 },
    { "cell_res_silica_sand_extra_change",     "res_silica_sand_extra_change_arr",     SlotDType::F32 },
    { "cell_res_phosphate_rock_extra_change",  "res_phosphate_rock_extra_change_arr",  SlotDType::F32 },
    { "cell_res_tin_ore_extra_change",         "res_tin_ore_extra_change_arr",         SlotDType::F32 },
    { "cell_res_lead_ore_extra_change",        "res_lead_ore_extra_change_arr",        SlotDType::F32 },
    { "cell_res_zinc_ore_extra_change",        "res_zinc_ore_extra_change_arr",        SlotDType::F32 },
    { "cell_res_manganese_ore_extra_change",   "res_manganese_ore_extra_change_arr",   SlotDType::F32 },
    { "cell_res_sulfur_extra_change",          "res_sulfur_extra_change_arr",          SlotDType::F32 },
    { "cell_res_flint_extra_change",           "res_flint_extra_change_arr",           SlotDType::F32 },
    { "cell_demo_thermal_gradient",            "demo_thermal_gradient_arr",            SlotDType::F32 },  // demo-only (gated on ClimateProfile.demo_thermal_gradient_enabled)
};

inline constexpr int BIND_TABLE_AUTOGEN_SIZE =
    sizeof(BIND_TABLE_AUTOGEN) / sizeof(BindEntry);

} // namespace pk
